"""add amenities and location fields to tour_packages

Revision ID: 06d41e87c58b
Revises: 8c3277fdd1a7
Create Date: 2026-06-12 11:43:50.130430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d41e87c58b'
down_revision = '8c3277fdd1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('location_description')
        batch_op.drop_column('amenities')

    # ### end Alembic commands ###
