"""add is_featured to tour_packages

Revision ID: 101eab78c911
Revises: a061d874a03c
Create Date: 2026-06-09 12:55:00.230713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101eab78c911'
down_revision = 'a061d874a03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tour_packages_is_featured'), ['is_featured'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_packages_is_featured'))
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
