"""Add itinerary field to tour packages

Revision ID: 3844c3a00bc0
Revises: 7ce05ca8c976
Create Date: 2026-08-11 12:13:45.083007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3844c3a00bc0'
down_revision = '7ce05ca8c976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itinerary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        batch_op.drop_column('itinerary')

    # ### end Alembic commands ###
