"""add session_token to users

Revision ID: 3cee47dfc5ac
Revises: bbb3d2515fa7
Create Date: 2026-07-15 10:12:26.204157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cee47dfc5ac'
down_revision = 'bbb3d2515fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_email_failed', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_token')

    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_column('confirmation_email_failed')

    # ### end Alembic commands ###
