"""add unsubscribe token to subscribers

Revision ID: 4f1a00641546
Revises: 607877ad8fa5
Create Date: 2026-09-19 14:16:11.420953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1a00641546'
down_revision = '607877ad8fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unsubscribe_token', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['unsubscribe_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('unsubscribe_token')

    # ### end Alembic commands ###
