"""add wishlist_items table

Revision ID: 7ce05ca8c976
Revises: b4d8f1a6c3e7
Create Date: 2026-08-10 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce05ca8c976'
down_revision = 'b4d8f1a6c3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('visa_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(package_id IS NOT NULL AND visa_id IS NULL) OR (package_id IS NULL AND visa_id IS NOT NULL)', name='ck_wishlist_exactly_one_target'),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visa_id'], ['visa_countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'package_id', name='uq_wishlist_user_package'),
    sa.UniqueConstraint('user_id', 'visa_id', name='uq_wishlist_user_visa')
    )
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_visa_id'), ['visa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_items_visa_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_package_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_created_at'))

    op.drop_table('wishlist_items')
    # ### end Alembic commands ###
