"""add mobile_path to hero_slides

Revision ID: 7d10bd5f82dd
Revises: d99e4ac1f090
Create Date: 2026-08-17 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d10bd5f82dd'
down_revision = 'd99e4ac1f090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_slides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_slides', schema=None) as batch_op:
        batch_op.drop_column('mobile_path')
    # ### end Alembic commands ###