"""Add indexes to package_reviews package_id and created_at

Revision ID: 7d9764b9ab92
Revises: cbfcd650aba7
Create Date: 2026-07-01 09:54:12.920960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9764b9ab92'
down_revision = 'cbfcd650aba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('inquiry_notifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('package_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_reviews_package_id'), ['package_id'], unique=False)

    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('testimonials_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('testimonials_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('package_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_reviews_package_id'))
        batch_op.drop_index(batch_op.f('ix_package_reviews_created_at'))

    with op.batch_alter_table('inquiry_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('inquiry_notifications_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
