"""add updated_at to packages and bookings

Revision ID: 8c3277fdd1a7
Revises: 101eab78c911
Create Date: 2026-06-12 10:14:41.431644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3277fdd1a7'
down_revision = '101eab78c911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
