"""add agents table and package routing fields

Revision ID: 8f5f96bfb999
Revises: df8e673abebf
Create Date: 2026-06-28 14:02:01.638010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5f96bfb999'
down_revision = 'df8e673abebf'
branch_labels = None
depends_on = None


def upgrade():
    # Create the agents table FIRST — tour_packages.assigned_agent_id
    # below has a foreign key pointing at it, so it must exist already.
    op.create_table('agents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=150), nullable=False),
        sa.Column('notes', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        # server_default backfills existing rows with 'domestic' so this
        # NOT NULL column doesn't fail against a table that already has data
        batch_op.add_column(sa.Column('package_type', sa.String(length=20), nullable=False, server_default='domestic'))
        batch_op.add_column(sa.Column('assigned_agent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tour_packages_assigned_agent_id'), ['assigned_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tour_packages_package_type'), ['package_type'], unique=False)
        batch_op.create_foreign_key(None, 'agents', ['assigned_agent_id'], ['id'])

    # Drop the server-side default now that existing rows are backfilled —
    # the app itself supplies 'domestic' as the default for new rows going forward.
    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        batch_op.alter_column('package_type', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_packages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tour_packages_package_type'))
        batch_op.drop_index(batch_op.f('ix_tour_packages_assigned_agent_id'))
        batch_op.drop_column('assigned_agent_id')
        batch_op.drop_column('package_type')

    op.drop_table('agents')
    # ### end Alembic commands ###