"""add visa_agent to site_settings

Revision ID: bb9a99652b27
Revises: 8f5f96bfb999
Create Date: 2026-06-28 15:14:25.001468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9a99652b27'
down_revision = '8f5f96bfb999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visa_agent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'agents', ['visa_agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visa_agent_id')

    # ### end Alembic commands ###
