"""add link_url to inquiry_notifications

Revision ID: bbb3d2515fa7
Revises: 7ed355b74822
Create Date: 2026-07-12 11:22:32.872521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb3d2515fa7'
down_revision = '7ed355b74822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_notifications', schema=None) as batch_op:
        batch_op.drop_column('link_url')

    # ### end Alembic commands ###
