"""Add package_id to inquiries

Revision ID: c474d574e45a
Revises: 3247ad4aa496
Create Date: 2026-06-03 16:51:55.439453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c474d574e45a'
down_revision = '3247ad4aa496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tour_packages', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###
