"""add travel_dates table

Revision ID: c61086505ac2
Revises: 7d10bd5f82dd
Create Date: 2026-08-24 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61086505ac2'
down_revision = '7d10bd5f82dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('travel_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_travel_dates_package_id'), ['package_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_travel_dates_package_id'))

    op.drop_table('travel_dates')
    # ### end Alembic commands ###