"""move visa agent flag from site_settings to agents

Revision ID: cbfcd650aba7
Revises: bb9a99652b27
Create Date: 2026-06-28 15:27:24.387938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfcd650aba7'
down_revision = 'bb9a99652b27'
branch_labels = None
depends_on = None


def upgrade():
    # server_default backfills existing agent rows with False so this
    # NOT NULL column doesn't fail against a table that already has data
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visa_agent', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Drop the server-side default now that existing rows are backfilled —
    # the app itself supplies False as the default for new rows going forward.
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('is_visa_agent', server_default=None)

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('site_settings_visa_agent_id_fkey'), type_='foreignkey')
        batch_op.drop_column('visa_agent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visa_agent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('site_settings_visa_agent_id_fkey'), 'agents', ['visa_agent_id'], ['id'])

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('is_visa_agent')

    # ### end Alembic commands ###