"""add itinerary_days table

Revision ID: d1da988c3400
Revises: 3844c3a00bc0
Create Date: 2026-08-14 17:44:25.109973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1da988c3400'
down_revision = '3844c3a00bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meals', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['tour_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itinerary_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_days_package_id'), ['package_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_days_package_id'))

    op.drop_table('itinerary_days')
    # ### end Alembic commands ###
