"""add inquiry_notifications table

Revision ID: df8e673abebf
Revises: 7c90eeeaeec0
Create Date: 2026-06-25 14:57:10.977652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8e673abebf'
down_revision = '7c90eeeaeec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiry_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquiry_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquiry_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiry_notifications_inquiry_id'), ['inquiry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiry_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiry_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inquiry_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_inquiry_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_inquiry_notifications_inquiry_id'))
        batch_op.drop_index(batch_op.f('ix_inquiry_notifications_created_at'))

    op.drop_table('inquiry_notifications')
    # ### end Alembic commands ###
