"""add region visa_type processing_time stay_validity documents_count to visa_country

Revision ID: e2b001aab8e4
Revises: 06d41e87c58b
Create Date: 2026-06-16 10:07:27.289016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b001aab8e4'
down_revision = '06d41e87c58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('visa_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('processing_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stay_validity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('documents_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_countries', schema=None) as batch_op:
        batch_op.drop_column('documents_count')
        batch_op.drop_column('stay_validity')
        batch_op.drop_column('processing_time')
        batch_op.drop_column('visa_type')
        batch_op.drop_column('region')

    # ### end Alembic commands ###
