"""Add reference_number to inquiries for tracking

Revision ID: e3f7a9c1d2b5
Revises: 3247ad4aa496
Create Date: 2026-06-04 10:15:30.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f7a9c1d2b5'
down_revision = '3247ad4aa496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_number', sa.String(length=20), nullable=True))
        batch_op.create_index('ix_inquiries_reference_number', ['reference_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_index('ix_inquiries_reference_number')
        batch_op.drop_column('reference_number')

    # ### end Alembic commands ###
