"""add oauth fields to user, make password nullable

Revision ID: ff76753bca57
Revises: 7d9764b9ab92
Create Date: 2026-07-02 10:05:08.574135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff76753bca57'
down_revision = '7d9764b9ab92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_oauth_provider'), ['oauth_provider'], unique=False)
        batch_op.create_unique_constraint('uq_users_oauth_identity', ['oauth_provider', 'oauth_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_oauth_identity', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_oauth_provider'))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
